export const TypeKeys = {
    FETCH_USER_REQUESTED:'FETCH_USER_REQUEST',
    FETCH_USER_SUCCEEDED:'FETCH_USER_SUCCEEDED',
    FETCH_USER_FAILED:'FETCH_USER_FAILED',
    FETCH_USER_CACHED:'FETCH_USER_CACHED',
}